version: '2'

services:
  db:
    image: postgres:latest
    restart: always
    volumes: 
      - /var/lib/postgresql/data
  web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

