# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170723_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_type',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
